"""
Django settings for blog project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
=======
Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
<<<<<<< HEAD
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cq8q95vmqzur&1v03b!7bnm17dit90f$v^x_-&%+9paahc4n6^'
=======
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-(+&&sy&!u)&f7=ywcmr0b+x!tgfb75cjw3f_y9@)9ve39j-gg'
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

<<<<<<< HEAD
INSTALLED_APPS = [
=======
INSTALLED_APPS = (
    'blog',
    'articles',
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'blog',
    'articles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
=======
)

MIDDLEWARE_CLASSES = (
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
<<<<<<< HEAD
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
=======
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


<<<<<<< HEAD
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
=======
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [

    os.path.join(BASE_DIR, "static"),
    '/var/www/html/blog/blog/static',

]
=======
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
>>>>>>> 7e88efda4da329363e4b3c4565a61ee381ba6e4d
